server:
  port: 5555
  
eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      
zuul:
  # 为所有路由增加前缀
  # prifix: /api
  routes:
    consumerservice: /myconsumer/**
    mystaticconsumer:
      path: /mystaticconsumer/**
      url: http://localhost:8081/